global:
  scrape_interval: 1m
  scrape_timeout: 10s

rule_files:
  - 'alerts.localhost.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ['prometheus:9090']

- job_name: node-exporter
  static_configs:
  - targets: ['node-exporter:9100']

- job_name: dockerd-exporter
  static_configs:
  - targets: [172.18.0.1:9323]

- job_name: cadvisor
  static_configs:
  - targets: ['cadvisor:8080']

- job_name: traefik
  static_configs:
  - targets: ['traefik:8080']
